import { PEOPLE_INFORMATION_TYPE } from 'types/people/people-information';

//filter 메서드를 사용하여 데이터를 걸러내는 과정 자체는 브라우저에서 매우 빠르게 처리되므로, 수백 명의 알럼나이 항목은 여기서 관리해도 됨. 천 명 넘어갈 때 새로운 파일로 나누기.
//나중에는 virtualization or Memoization을 활용하여 렌더링 속도 최적화도 가능

export const PEOPLE_ITEMS = {
    TEN: 10,
    ELEVEN: 11,
    TWELVE: 12,
};

export enum DEPARTMENT {
    //한국어 기준 ㄱㄴㄷ순
    BUSINESS = '경영학과',
    EDUCATION = '교육학과',
    KOREA_LANGUAGE_AND_LITERATURE = '국어국문학과',
    RUSSIAN_LANGUAGE_AND_LITERATURE = '노어노문학과',
    DESIGN = '디자인조형학부',
    MEDIA = '미디어학부',
    BIO_MEDICAL_ENGINEERING = '바이오의공학부',
    HEALTH_ENVIRONMENTAL_CONVERGENCE_SCIENCE = '보건환경융합과학부',
    PSYCHOTHERAPY = '심리학과',
    SOCIOLOGY = '사회학과',
    BIOLOGICAL_ENGINEERING = '생명공학부',
    JAPANESE_LANGUAGE_AND_LITERATURE = '일어일문학과',
    ENGLISH_EDUCATION = '영어교육학과',
    CONVERGENCE_ENERGY_ENGINEERING = '융합에너지공학과',
    ELECTRONIC_ELECTRICAL_ENGINEERING = '전기전자공학부',
    EARTH_ENVIRONMENTAL_SCIENCE = '지구환경과학부',
    CHINESE_LANGUAGE_AND_LITERATURE = '중어중문학과',
    PHYSICAL_EDUCATION = '체육교육과',
    COMPUTER = '컴퓨터학과',
    STATISTICS = '통계학과',
    CHINESE_CHARACTER = '한문학과',
}

export enum MANAGEMENT_TEAM_POSITION {
    REPRESENTATICE = '대표',
    EXECUTIVE = '임원진',
    EDUCATION = '학술부',
    PROJECT_MANAGER = '기획부',
    NORMAL = '학회원',
    // HAKHWEWON = '학회원',
}

export enum DONGULDONGUL_TEAM_NUM {
    FIRST  = '1조',
    SECOND = '2조',
    THIRD  = '3조',
    FOURTH = '4조',
    FIFTH  = '5조',
    SIXTH  = '6조',
}

export enum HACHATHON_TEAM_NUM {
    FIRST  = '1조',
    SECOND = '2조',
    THIRD  = '3조',
    FOURTH = '4조',
    FIFTH  = '5조',
    SIXTH  = '6조',
}
export enum PRODUCTDAY_TEAM_NUM {
    FIRST  = '1조',
    SECOND = '2조',
    THIRD  = '3조',
    FOURTH = '4조',
    FIFTH  = '5조',
    SIXTH  = '6조',
}
export enum DEMODAY_TEAM_NUM {
    FIRST  = '1조',
    SECOND = '2조',
    THIRD  = '3조',
    FOURTH = '4조',
    FIFTH  = '5조',
    SIXTH  = '6조',
}

export const PEOPLE_INFORMATION: PEOPLE_INFORMATION_TYPE[] = [
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '김나영',
        department: DEPARTMENT.MEDIA,
        classOf: 20,
        imgSrc: '/images/profile/10gen/10기_김나영.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.EDUCATION,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '김민지',
        department: DEPARTMENT.MEDIA,
        classOf: 18,
        imgSrc: '/images/profile/10gen/10기_김민지.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '김지욱',
        department: DEPARTMENT.BUSINESS,
        classOf: 17,
        imgSrc: '/images/profile/10gen/10기_김지욱.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.EDUCATION,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '김채현',
        department: DEPARTMENT.BIO_MEDICAL_ENGINEERING,
        classOf: 20,
        imgSrc: '/images/profile/10gen/10기_김채현.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '김하경',
        department: DEPARTMENT.BIOLOGICAL_ENGINEERING,
        classOf: 19,
        imgSrc: '/images/profile/10gen/10기_김하경.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '문지후',
        department: DEPARTMENT.EDUCATION,
        classOf: 20,
        imgSrc: '/images/profile/10gen/10기_문지후.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.EDUCATION,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '박견우',
        department: DEPARTMENT.HEALTH_ENVIRONMENTAL_CONVERGENCE_SCIENCE,
        classOf: 18,
        imgSrc: '/images/profile/10gen/10기_박견우.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '박소정',
        department: DEPARTMENT.DESIGN,
        classOf: 19,
        imgSrc: '/images/profile/10gen/10기_박소정.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '백민기',
        department: DEPARTMENT.KOREA_LANGUAGE_AND_LITERATURE,
        classOf: 17,
        imgSrc: '/images/profile/10gen/10기_백민기.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.EDUCATION,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '손수원',
        department: DEPARTMENT.COMPUTER,
        classOf: 19,
        imgSrc: '/images/profile/10gen/10기_손수원.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '송명훈',
        department: DEPARTMENT.COMPUTER,
        classOf: 19,
        imgSrc: '/images/profile/10gen/10기_송명훈.png',
        secondMajor: '자전',
        managementTeam: MANAGEMENT_TEAM_POSITION.REPRESENTATICE,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '양휘민',
        department: DEPARTMENT.JAPANESE_LANGUAGE_AND_LITERATURE,
        classOf: 20,
        imgSrc: '/images/profile/10gen/10기_양휘민.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '엄혜영',
        department: DEPARTMENT.HEALTH_ENVIRONMENTAL_CONVERGENCE_SCIENCE,
        classOf: 19,
        imgSrc: '/images/profile/10gen/10기_엄혜영.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.PROJECT_MANAGER,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '윤정윤',
        department: DEPARTMENT.RUSSIAN_LANGUAGE_AND_LITERATURE,
        classOf: 18,
        imgSrc: '/images/profile/10gen/10기_윤정윤.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.REPRESENTATICE,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '이소희',
        department: DEPARTMENT.STATISTICS,
        classOf: 20,
        imgSrc: '/images/profile/10gen/10기_이소희.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.EDUCATION,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '이영서',
        department: DEPARTMENT.BUSINESS,
        classOf: 21,
        imgSrc: '/images/profile/10gen/10기_이영서.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.PROJECT_MANAGER,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '이예원',
        department: DEPARTMENT.ELECTRONIC_ELECTRICAL_ENGINEERING,
        classOf: 19,
        imgSrc: '/images/profile/10gen/10기_이예원.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '이유진',
        department: DEPARTMENT.SOCIOLOGY,
        classOf: 18,
        imgSrc: '/images/profile/10gen/10기_이유진.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '이지수',
        department: DEPARTMENT.MEDIA,
        classOf: 19,
        imgSrc: '/images/profile/10gen/10기_이지수.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '이지은',
        department: DEPARTMENT.PSYCHOTHERAPY,
        classOf: 20,
        imgSrc: '/images/profile/10gen/10기_이지은.png',
        masterDegree: '석사',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '전민철',
        department: DEPARTMENT.BUSINESS,
        classOf: 17,
        imgSrc: '/images/profile/10gen/10기_전민철.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '전성운',
        department: DEPARTMENT.ELECTRONIC_ELECTRICAL_ENGINEERING,
        classOf: 22,
        imgSrc: '/images/profile/10gen/10기_전성운.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.EDUCATION,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '정지우',
        department: DEPARTMENT.BUSINESS,
        classOf: 20,
        imgSrc: '/images/profile/10gen/10기_정지우.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.EXECUTIVE,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '주장규',
        department: DEPARTMENT.PSYCHOTHERAPY,
        classOf: 21,
        imgSrc: '/images/profile/10gen/10기_주장규.png',
        masterDegree: '석사',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '차수지',
        department: DEPARTMENT.EARTH_ENVIRONMENTAL_SCIENCE,
        classOf: 18,
        imgSrc: '/images/profile/10gen/10기_차수지.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '한성수',
        department: DEPARTMENT.KOREA_LANGUAGE_AND_LITERATURE,
        classOf: 17,
        imgSrc: '/images/profile/10gen/10기_한성수.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '한예진',
        department: DEPARTMENT.KOREA_LANGUAGE_AND_LITERATURE,
        classOf: 21,
        imgSrc: '/images/profile/10gen/10기_한예진.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.TEN,
        name: '홍세린',
        department: DEPARTMENT.ENGLISH_EDUCATION,
        classOf: 18,
        imgSrc: '/images/profile/10gen/10기_홍세린.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.PROJECT_MANAGER,
    },

    /////////////////////////////////////////////////
    // 여기서부터 11기
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '강동혁',
        department: DEPARTMENT.COMPUTER,
        classOf: 20,
        imgSrc: '/images/profile/11gen/11기_강동혁.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.EXECUTIVE,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '김경진',
        department: DEPARTMENT.ELECTRONIC_ELECTRICAL_ENGINEERING,
        classOf: 22,
        imgSrc: '/images/profile/11gen/11기_김경진.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '김지호',
        department: DEPARTMENT.ELECTRONIC_ELECTRICAL_ENGINEERING,
        classOf: 18,
        imgSrc: '/images/profile/11gen/11기_김지호.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '김태균',
        department: DEPARTMENT.PHYSICAL_EDUCATION,
        classOf: 22,
        imgSrc: '/images/profile/11gen/11기_김태균.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.EXECUTIVE,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '나성희',
        department: DEPARTMENT.BUSINESS,
        classOf: 21,
        imgSrc: '/images/profile/11gen/11기_나성희.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.PROJECT_MANAGER,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '박경빈',
        department: DEPARTMENT.MEDIA,
        classOf: 19,
        imgSrc: '/images/profile/11gen/11기_박경빈.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.REPRESENTATICE,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '박민수',
        department: DEPARTMENT.BUSINESS,
        classOf: 19,
        imgSrc: '/images/profile/11gen/11기_박민수.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '박소정',
        department: DEPARTMENT.BUSINESS,
        classOf: 21,
        imgSrc: '/images/profile/11gen/11기_박소정.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.EXECUTIVE,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '박준성',
        department: DEPARTMENT.CHINESE_LANGUAGE_AND_LITERATURE,
        classOf: 18,
        imgSrc: '/images/profile/11gen/11기_박준성.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '손예원',
        department: DEPARTMENT.COMPUTER,
        classOf: 21,
        imgSrc: '/images/profile/11gen/11기_손예원.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.EDUCATION,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '유명균',
        department: DEPARTMENT.BUSINESS,
        classOf: 19,
        imgSrc: '/images/profile/11gen/11기_유명균.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '이명은',
        department: DEPARTMENT.BUSINESS,
        classOf: 20,
        imgSrc: '/images/profile/11gen/11기_이명은.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '이보름',
        department: DEPARTMENT.ELECTRONIC_ELECTRICAL_ENGINEERING,
        classOf: 22,
        imgSrc: '/images/profile/11gen/11기_이보름.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.EDUCATION,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '이영주',
        department: DEPARTMENT.BUSINESS,
        classOf: 19,
        imgSrc: '/images/profile/11gen/11기_이영주.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '이영찬',
        department: DEPARTMENT.ENGLISH_EDUCATION,
        classOf: 18,
        imgSrc: '/images/profile/11gen/11기_이영찬.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.EDUCATION,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '이혁준',
        department: DEPARTMENT.COMPUTER,
        classOf: 21,
        imgSrc: '/images/profile/11gen/11기_이혁준.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.EDUCATION,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '임소현',
        department: DEPARTMENT.ENGLISH_EDUCATION,
        classOf: 20,
        imgSrc: '/images/profile/11gen/11기_임소현.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '정석민',
        department: DEPARTMENT.BIOLOGICAL_ENGINEERING,
        classOf: 19,
        imgSrc: '/images/profile/11gen/11기_정석민.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.EDUCATION,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '정효진',
        department: DEPARTMENT.CHINESE_CHARACTER,
        classOf: 21,
        imgSrc: '/images/profile/11gen/11기_정효진.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '조수아',
        department: DEPARTMENT.CONVERGENCE_ENERGY_ENGINEERING,
        classOf: 22,
        imgSrc: '/images/profile/11gen/11기_조수아.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.EDUCATION,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '조원경',
        department: DEPARTMENT.CHINESE_LANGUAGE_AND_LITERATURE,
        classOf: 20,
        imgSrc: '/images/profile/11gen/11기_조원경.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.PROJECT_MANAGER,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '채윤석',
        department: DEPARTMENT.CHINESE_LANGUAGE_AND_LITERATURE,
        classOf: 19,
        imgSrc: '/images/profile/11gen/11기_채윤석.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '최기성',
        department: DEPARTMENT.PSYCHOTHERAPY,
        classOf: 17,
        imgSrc: '/images/profile/11gen/11기_최기성.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '최성호',
        department: DEPARTMENT.BUSINESS,
        classOf: 19,
        imgSrc: '/images/profile/11gen/11기_최성호.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
    },
    {
        gen: PEOPLE_ITEMS.ELEVEN,
        name: '최유빈',
        department: DEPARTMENT.MEDIA,
        classOf: 20,
        imgSrc: '/images/profile/11gen/11기_최유빈.png',
        managementTeam: MANAGEMENT_TEAM_POSITION.EXECUTIVE,
    },
    {
        gen: PEOPLE_ITEMS.TWELVE,
        name: '배연준',
        department: DEPARTMENT.ELECTRONIC_ELECTRICAL_ENGINEERING,
        classOf: 20,
        imgSrc: '/images/profile/12gen/12기_배연준.JPG',
        managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
        linkedIn: 'https://www.linkedin.com/in/%EC%97%B0%EC%A4%80-%EB%B0%B0-41a1b1311/',
        donguldongul: DONGULDONGUL_TEAM_NUM.FIRST,
        hackathon: HACHATHON_TEAM_NUM.FIRST,
        productDay: PRODUCTDAY_TEAM_NUM.THIRD,
        demoDay: DEMODAY_TEAM_NUM.FIRST,
        nextTag : ['#열정','#책임감','#팀워크'],
    },
];
